/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author roszkopf.a.lena
 */
public class GuiNezet extends javax.swing.JFrame {

    public void megjelenit(String uzenet){
        txtaJatek.setText(uzenet);
    }
    
    public void visszajelzes(String uzenet){
        JOptionPane.showMessageDialog(rootPane,uzenet);
    }

    public JButton getBtnValasztas() {
        return btnValasztas;
    }
    
    public int bekeres(){
        int v = -1;
        if(rgbArany.isSelected()){
            v= 0;
        }else if(rgbEzust.isSelected()){
            v= 1;
        }else{
            v= 2;
        }
        
        return v;
    }
    
    public GuiNezet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaJatek = new javax.swing.JTextArea();
        rgbArany = new javax.swing.JRadioButton();
        rgbEzust = new javax.swing.JRadioButton();
        rgbBronz = new javax.swing.JRadioButton();
        btnValasztas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 232, 232));

        txtaJatek.setColumns(20);
        txtaJatek.setLineWrap(true);
        txtaJatek.setRows(5);
        jScrollPane1.setViewportView(txtaJatek);

        buttonGroup1.add(rgbArany);
        rgbArany.setText("Aranyláda");

        buttonGroup1.add(rgbEzust);
        rgbEzust.setText("Ezüstláda");

        buttonGroup1.add(rgbBronz);
        rgbBronz.setText("Bronzláda");

        btnValasztas.setText("Választás");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rgbBronz)
                        .addGap(107, 107, 107)
                        .addComponent(btnValasztas))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rgbEzust)
                        .addComponent(rgbArany)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgbArany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgbEzust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgbBronz)
                    .addComponent(btnValasztas))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValasztas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rgbArany;
    private javax.swing.JRadioButton rgbBronz;
    private javax.swing.JRadioButton rgbEzust;
    private javax.swing.JTextArea txtaJatek;
    // End of variables declaration//GEN-END:variables
}
